name: video-factorisation

dependencies:
  - python=3.8.5
  - numpy=1.20.1
  - matplotlib=3.3.4
  - pip=20.2.4
  - pillow=8.2.0
  - imageio=2.9.0
  - pip:
    - torch==1.4.0
    - torchvision==0.5.0
    - tqdm==4.60.0
